FROM debian:jessie

MAINTAINER TANGO Controls team <tango@esrf.fr>

RUN apt-get update && apt-get install -y apt-utils

RUN apt-get update && apt-get install -y build-essential cmake

RUN apt-get update && apt-get install -y libomniorb4-dev libcos4-dev libomnithread3-dev libzmq-dev