#!/bin/bash

#
# remove different echo command behaviour on different OS
#
if test "`echo -e xxx`" = "xxx"
then
    echo="echo -e"
else
    echo=echo
fi

if [ $# = 0 ]
then
	$echo "\nusage:  runtest ds_system\n"
	$echo "ds_system can be ubuntu904, python or jenkins"
	exit 1
fi

#
# test host
#

UBUNTU904_HOST=pcantares
PYTHON_HOST=controls01

HOST=`hostname`
SERV_NAME=devTest


case $1 in
ubuntu904 )
	if [ $HOST != $UBUNTU904_HOST ]
	then
		$echo "For ubuntu 9.04, test should run on "$UBUNTU904_HOST
		exit 1
	fi
	DIR=bin/ubuntu904
	;;
#
python )
	if [ $HOST != $PYTHON_HOST ]
	then
		$echo "For python, test should run on "$PYTHON_HOST
		exit 1
	fi
	DIR=suse93
	;;
#
jenkins )
	BASE_DIR=$2
	for i in $NODE_LABELS
	do
		echo $i
		if [ $i = "ubuntu10.04" ]
		then
			echo "Ubuntu 10.04 OS"
			DIR="$BASE_DIR/ubuntu1004/bin"
		fi
	
		if [ $i = "solaris10" ]
		then
			echo "Solaris 10 OS"
			DIR="$BASE_DIR/solaris10_CC/bin"
		fi
	
		if [ $i = "redhate5" ]
		then
			echo "redhate 5 OS"
			DIR="$BASE_DIR/redhate5/bin"
		fi
	done
	;;
#
* )
	$echo "\nunknown system"
	exit 1
	;;
esac

check_return_value () {
if [ $1 != "0" ]
then
	echo "Test Suite FAILED !!!!!!!!!!!!!!!!!!"
	echo "Leaving test suite, try to fix it"
	exit -1
fi
}

#
# First, test device server startup sequence
#

$echo "\nTesting executing command asynchronously (polling way)"
$DIR/asyn_cmd dev/test/10
ret=$?
check_return_value $ret
#
$echo "\nTesting reading attribute asynchronously (polling way)"
$DIR/asyn_attr dev/test/10
ret=$?
check_return_value $ret
#
$echo "\nTesting reading several attributes asynchronously (polling way)"
$DIR/asyn_attr_multi dev/test/10
ret=$?
check_return_value $ret
#
$echo "\nTesting writing attribute asynchronously (polling way)"
$DIR/asyn_write_attr dev/test/10
ret=$?
check_return_value $ret
#
$echo "\nTesting writing several attributes asynchronously (polling way)"
$DIR/asyn_write_attr_multi dev/test/10
ret=$?
check_return_value $ret
#
$echo "\nTesting mixed asynchronous and callback modes (1)"
$DIR/asyn_cb
ret=$?
check_return_value $ret
#
$echo "\nTesting mixed asynchronous and callback modes (2)"
$DIR/asyn_cb2
ret=$?
check_return_value $ret
#
$echo "\nTesting executing command asynchronously (callback way)"
$DIR/asyn_cb_cmd dev/test/10
ret=$?
check_return_value $ret
#
$echo "\nTesting reading attribute asynchronously (callback way)"
$DIR/asyn_attr_cb dev/test/10
ret=$?
check_return_value $ret
#
$echo "\nTesting writing attribute asynchronously (callback way)"
$DIR/asyn_write_cb dev/test/10
ret=$?
check_return_value $ret
#
$echo "\nTesting automatic callback mode"
$DIR/auto_asyn_cmd dev/test/10
ret=$?
check_return_value $ret
#
